package com.call_logs.system.enums;

public enum Status {

	  PENDING,
	  PROCEED,
	  CANCEL,
	  SENT_TO_CUSTOMER,
	  RECEIVED_IN_OFFICE,
	  EMPLOYEE_RECEIVED, DISPATCHED,
	   WORK_STARTED,
	    WORK_COMPLETED, BILL_PENDING, PAID, PARTIALLY_PAID
}
